server:
  servlet:
    context-path: "/api"
  error:
    include-message: always

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/finance"
    username: dev
    password: dev129
  jpa:
    hibernate:
      ddl-auto: none
    #show-sql: true // enable if you try to optimize query to db (customize hibernate)
    properties:
      hibernate:
        #generate_statistics: true // enable if you try to optimize query to db (customize hibernate)
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  task:
    scheduling:
      pool:
        size: 5

springdoc:
  title: @project.name@
  version: @project.version@
  description: @project.description@
  api-docs:
    enabled: true

goal:
  batch-size: 5
transaction:
  batch-size: 5
